### ISSUE TITLE
Unable to log in using provided credentials

### ISSUE THREAD

**Issue by Gentronicus** [Wiibuntu/Xubuntu-9.04-Wii#1]
Hello!
On a fresh install, I can't seem to log in using the credentials in the readme.
Is the readme wrong, or am I just typing it wrong the last 7 times?

**Comment by Wiibuntu** [comment]
Login is case sensitive. When it asks for a login type "ubuntu" without quotes. And then the password is "Wiibuntu9" without quotes.

**Comment by alexwiedermann** [comment]
Same issue here

**Comment by RealPortalPlayer** [comment]
The password is actually "1985" (without quotes)

**Comment by Wiibuntu** [comment]
Fixed in new release, password was set incorrectly.
