### ISSUE TITLE
BalenaEtcher Errors out when flashing. Credentials aren't working either.

### ISSUE THREAD

**Issue by CABLE353** [Wiibuntu/Xubuntu-9.04-Wii#4]
I tried to use BalenaEtcher to flash to my sd card & to my usb flash drive, both with enough storage & I made sure they were either on FAT32 or unallocated for the image. When BalenaEtcher started to flash it would complete but when it was on the verification step it would error out right around 60-75% of the way done. I decided to try the errored out disk anyway. Everything looked fine but when it came to login the 'ubuntu' username & the 'Wiibuntu9' password were incorrect. Is it possible the image file corrupted at the time of correctly writing the login files?

**Comment by Crispymug** [comment]
I was told the password listed was false and it was actually “1985”. It worked for me when I did it a week ago so hopefully that fixes the issue.

**Comment by CABLE353** [comment]
Yes it did. I now have my Priiloader to autoboot to the .dol file so I can surprise & confuse people.  🤣🤣🤣

**Comment by Wiibuntu** [comment]
Fixed in new release, password was set incorrectly.
